import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class ReportTemplateServiceImpl {
  static pw.Widget buildHeader({
    required String title,
    required String subtitle,
    pw.ImageProvider? logo,
  }) {
    return pw
        .Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.center, children: [
        if (logo != null) ...[
          pw.Image(logo, width: 42, height: 42),
          pw.SizedBox(width: 10),
        ],
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('VINAYAK LOGISTICS',
              style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900)),
          pw.Text('SmartLoad System',
              style:
                  const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
        ]),
      ]),
      pw.SizedBox(height: 20),
      pw.Divider(),
      pw.SizedBox(height: 10),
      pw.Text(title,
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
      pw.Text(subtitle,
          style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey600)),
      pw.SizedBox(height: 20),
    ]);
  }

  static pw.Widget buildFooter(pw.Context context) {
    return pw.Column(children: [
      pw.Divider(),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Vinayak SmartLoad',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
        ],
      )
    ]);
  }

  static pw.Widget buildSignatures({
    String supervisorName = 'Not provided',
  }) {
    return pw.Container(
        margin: const pw.EdgeInsets.only(top: 40),
        child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(children: [
                pw.Text(supervisorName,
                    style: pw.TextStyle(
                        fontSize: 11, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 4),
                pw.Container(
                    width: 150,
                    decoration: const pw.BoxDecoration(
                        border: pw.Border(bottom: pw.BorderSide(width: 1)))),
                pw.SizedBox(height: 5),
                pw.Text('Signature', style: const pw.TextStyle(fontSize: 12)),
              ]),
              pw.Column(children: [
                pw.Container(
                    width: 150,
                    decoration: const pw.BoxDecoration(
                        border: pw.Border(bottom: pw.BorderSide(width: 1)))),
                pw.SizedBox(height: 5),
                pw.Text('Manager Signature',
                    style: const pw.TextStyle(fontSize: 12)),
              ])
            ]));
  }
}
